### ISSUE TITLE
Enable GitHub Pages for index.html

### ISSUE THREAD

**Issue by jvanulde** [OpenDRR/ogc-api-features-leaflet#2]

**Comment by anthonyfok** [comment]
Hi Joost (@jvanulde),

Awesome interactive Leaflet page!

I was able to enable GitHub Pages for index.html
on a personal fork at https://github.com/anthonyfok/ogc-api-features-leaflet
by going to ⚙️ Setting > Options > GitHub Pages (near the bottom),
and under the Source heading,
change "None" to "main", and press the "Save" button,
and soon the index.html became accessible as-is (no Jekyll processing)
at https://anthonyfok.github.io/ogc-api-features-leaflet/
thanks to GitHub Pages static website hosting.

Here is a video demo of me doing the above:
* https://www.youtube.com/watch?v=OytnB05ltAY

But I'm sure you knew how to do that already as you must have done it before.

So, that got me wondering: Are you thinking of:
* just having this GitHub Pages enabled so it may be displayed on other pages (organization site, or /data, etc.) with the use of an `iframe`?  Or
* adding GCWeb theme and process it using Jekyll?  Or
* any other ideas?  :grin:

Thanks!

**Comment by jvanulde** [comment]
I was thinking that this example and others will be collected somehow on our organization page under developer samples or something like that. So perhaps this isn't the right place to host this via GitHub pages.

**Comment by jvanulde** [comment]
Closing for now. To be discussed once we have a strategy for the organization page.
